name: ufs_mt
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg:
  google_fonts: ^5.1.0
  glassmorphism_ui:


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueMedium.otf

  assets:
    - assets/images/

